AWSTemplateFormatVersion: '2010-09-09'
Resources:
  customVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/19
#
# Public subnets
#
  subnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.0.0/23
      AvailabilityZone: "ap-southeast-2a"
      Tags:
      - Key: Name
        Value: subnet-public-a

  subnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.2.0/23
      AvailabilityZone: "ap-southeast-2b"
      Tags:
      - Key: Name
        Value: subnet-public-b

  subnetPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.4.0/23
      AvailabilityZone: "ap-southeast-2c"
      Tags:
      - Key: Name
        Value: subnet-public-c
#
# Appliction subnets
#

  subnetAppA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.6.0/23
      AvailabilityZone: "ap-southeast-2a"
      Tags:
      - Key: Name
        Value: subnet-app-a

  subnetAppB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.8.0/23
      AvailabilityZone: "ap-southeast-2b"
      Tags:
      - Key: Name
        Value: subnet-app-b

  subnetAppC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.10.0/23
      AvailabilityZone: "ap-southeast-2c"
      Tags:
      - Key: Name
        Value: subnet-app-c
#
# Data subnets
#
  subnetDataA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.12.0/23
      AvailabilityZone: "ap-southeast-2a"
      Tags:
      - Key: Name
        Value: subnet-data-a

  subnetDataB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.14.0/23
      AvailabilityZone: "ap-southeast-2b"
      Tags:
      - Key: Name
        Value: subnet-data-b

  subnetDataC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.16.0/23
      AvailabilityZone: "ap-southeast-2c"
      Tags:
      - Key: Name
        Value: subnet-data-c

#
# NAT subnets
#
  subnetNatA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.18.0/28
      AvailabilityZone: "ap-southeast-2a"
      Tags:
      - Key: Name
        Value: subnet-nat-a

  subnetNatB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.18.16/28
      AvailabilityZone: "ap-southeast-2b"
      Tags:
      - Key: Name
        Value: subnet-nat-b

  subnetNatC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: customVPC
      CidrBlock: 10.0.18.32/28
      AvailabilityZone: "ap-southeast-2c"
      Tags:
      - Key: Name
        Value: subnet-nat-c

#
# Internet gateway
#

  internetGatewayCustom:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: igw-custom

  attachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref internetGatewayCustom
      VpcId: !Ref customVPC

#
# Elastic IPs for NAT gateways
#

  elasticIPNatA:
    Type: AWS::EC2::EIP
    DependsOn: attachInternetGateway
    Properties:
      Domain: !Ref customVPC

  elasticIPNatB:
    Type: AWS::EC2::EIP
    DependsOn: attachInternetGateway
    Properties:
      Domain: !Ref customVPC

  elasticIPNatC:
    Type: AWS::EC2::EIP
    DependsOn: attachInternetGateway
    Properties:
      Domain: !Ref customVPC

#
# NAT gateways
#

  natGatewayA:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt elasticIPNatA.AllocationId
      SubnetId: !Ref subnetNatA
      Tags: 
        - Key: Name
          Value: nat-gateway-a

  natGatewayB:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt elasticIPNatB.AllocationId
      SubnetId: !Ref subnetNatB
      Tags: 
        - Key: Name
          Value: nat-gateway-b

  natGatewayC:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt elasticIPNatC.AllocationId
      SubnetId: !Ref subnetNatC
      Tags: 
        - Key: Name
          Value: nat-gateway-c

#
# Public route table
#
  routeTablePublic:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-public

  routePublicInternetGateway:
    Type: AWS::EC2::Route
    DependsOn: attachInternetGateway
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGatewayCustom
      RouteTableId: !Ref routeTablePublic

  subnetRoutePublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTablePublic
      SubnetId: !Ref subnetPublicA

  subnetRoutePublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTablePublic
      SubnetId: !Ref subnetPublicB

  subnetRoutePublicC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTablePublic
      SubnetId: !Ref subnetPublicC

#
# Application route tables
#

  routeTableAppA:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-app-a

  routeAppNatGatewayA:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayA
      RouteTableId: !Ref routeTableAppA

  subnetRouteAppA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableAppA
      SubnetId: !Ref subnetAppA

  routeTableAppB:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-app-b

  routeAppNatGatewayB:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayB
      RouteTableId: !Ref routeTableAppB

  subnetRouteAppB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableAppB
      SubnetId: !Ref subnetAppB

  routeTableAppC:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-app-c

  routeAppNatGatewayC:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayC
      RouteTableId: !Ref routeTableAppC

  subnetRouteAppC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableAppC
      SubnetId: !Ref subnetAppC

#
# Data route tables
#
  routeTableDataA:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-data-a

  routeDataNatGatewayA:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayA
      RouteTableId: !Ref routeTableDataA

  subnetRouteDataA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableDataA
      SubnetId: !Ref subnetDataA

  routeTableDataB:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-data-b

  routeDataNatGatewayB:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayB
      RouteTableId: !Ref routeTableDataB

  subnetRouteDataB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableDataB
      SubnetId: !Ref subnetDataB

  routeTableDataC:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-data-c

  routeDataNatGatewayC:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref natGatewayC
      RouteTableId: !Ref routeTableDataC

  subnetRouteDataC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableDataC
      SubnetId: !Ref subnetDataC

#
# NAT route tables
#
  routeTableNat:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: route-table-nat

  routeNatInternetGateway:
    Type: AWS::EC2::Route
    DependsOn: attachInternetGateway
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGatewayCustom
      RouteTableId: !Ref routeTableNat

  subnetRouteNatA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableNat
      SubnetId: !Ref subnetNatA

  subnetRouteNatB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableNat
      SubnetId: !Ref subnetNatB

  subnetRouteNatC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref routeTableNat
      SubnetId: !Ref subnetNatC